version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - cd frontend
      - npm install
  build:
    commands:
      - echo REACT_APP_AWS_ACCESS_KEY_ID=${REACT_APP_AWS_ACCESS_KEY_ID} >> .env
      - echo REACT_APP_AWS_SECRET_ACCESS_KEY=${REACT_APP_AWS_SECRET_ACCESS_KEY} >> .env
      - echo REACT_APP_AWS_REGION=${REACT_APP_AWS_REGION} >> .env
      - echo REACT_APP_AWS_BUCKET=${REACT_APP_AWS_BUCKET} >> .env
      - echo "Building the React application"
      - npm run build
  post_build:
    commands:
      - echo "Build completed on `date`"
artifacts:
  files:
    - '**/*'
  base-directory: frontend/build