import React from "react";
import Highlights from "../component/Highlights";
import icon from "../Picture-1.jpg";

class MainPage extends React.Component {
    render(){
        return (
            <div className="mainClass">
                <div className="main-content">
                    <h1>Project Highlights</h1>
                    <div className="project-highlights-container">
                        <p className="project-highlights">Ratings and qualitative insights generated by NLP techniques</p>
                        <p className="project-highlights">A user-friendly dashboard for ESG performance</p>
                        <p className="project-highlights">Risk modelling techniques in managing exposure to ESG-related risks</p>
                        <p className="project-highlights">A full-stack scalable modern web application</p>
                    </div>     
                </div>
                {/* <Highlights /> */}
            </div>
        )
    }
}

export default MainPage;