import React from "react";
import icon from "../Picture-1.jpg";

class MainPage extends React.Component {
    render() {
        return (
            <div className="main-content">
                <div style= {{display: "flex", flexDirection: "column", alignItems: "center"}}>
                    <h1>ESGenius</h1>
                    <p className="project-description">
                        ESG Data-Driven Decision Support System <br />
                        Full-stack Web Application with Machine Learning
                    </p>
                </div>
                
                <div style= {{display: "flex", flexDirection: "column", alignItems: "center"}}> 
                    <h1>Project Highlights</h1>
                    <div className="project-highlights-container">
                        <p className="project-highlights">Ratings and qualitative insights generated by NLP techniques</p>
                        <p className="project-highlights">A user-friendly dashboard for ESG performance</p>
                        <p className="project-highlights">Risk modelling techniques in managing exposure to ESG-related risks</p>
                        <p className="project-highlights">A full-stack scalable modern web application</p>
                    </div>
                </div>
            </div>

        )
    }
}

export default MainPage;